<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#gerenciarPessoa">
    Adicionar
</button>
<div class="panel panel-default" style="margin-top: 5px">
    <div class="panel-heading">Listagem de Pessoas</div>

    <table class="table">
        <thead>
        <tr>
            <td width="40%">Nome</td>
            <td width="50%">Sobrenome</td>
            <td width="5%">Editar</td>
            <td width="5%">Excluir</td>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>


<!-- Modal -->
<div class="modal fade" id="gerenciarPessoa" tabindex="-1" role="dialog" aria-labelledby="gerenciarPessoaLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="gerenciarPessoaLabel">Cadastro da pessoa</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="form-pessoa" action="../adicionar.php" method="post">
                    <input type="hidden" name="id" >
                    <div class="form-group">
                        <label for="nome">Nome</label>
                        <input type="text" minlength="3" maxlength="50" class="form-control" id="nome" name="nome" aria-describedby="nomeHelp" placeholder="Nome da pessoa">
                        <small id="nomeHelp" class="form-text text-muted">Digite o primeiro nome. Mín: 3 dígitos, Máx: 50 dígitos.</small>
                    </div>
                    <div class="form-group">
                        <label for="sobrenome">Sobrenome</label>
                        <input type="text" minlength="3" maxlength="100" class="form-control" name="sobrenome" id="sobrenome" aria-describedby="sobrenomeHelp" placeholder="Sobrenome da pessoa">
                        <small id="sobrenomeHelp" class="form-text text-muted">Digite o sobrenome. Mín: 3 dígitos, Máx: 100 dígitos.</small>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
